title: MAL-Remainder

email: saihanumarahul66@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
    MALRemainder is an Application that could automate the process of 
    updating the list in MyAnimeList by regularly reminding to do that in a simple way.

# FOR GITHUB-PAGES
baseurl: "/MAL-Remainder/"
url: "https://rahularanger.github.io/"
# END FOR GITHUB - PAGES

# # FOR LOCAL SETUP
# url: ""
# baseurl: ""
# theme: "just-the-docs"
# # END FOR LOCAL SETUP

github_username: RahulARanger

toggle_color_scheme: dark     
toggle_page_url: "/"        
toggle_auto_mode: true   


remote_theme: pdmosses/just-the-docs@callouts

plugins:
    - jekyll-feed
    - jekyll-seo-tag

kramdown:
    syntax_highlighter_opts:
        block:
            line_numbers: false

compress_html:
    clippings: all
    comments: all
    endings: all
    startings: []
    blanklines: false
    profile: false
    # ignore:
    #   envs: all

# uncomment the below line in future for the logo
# logo: "/assets/images/just-the-docs.png"

search_enabled: true

search:
    # Split pages into sections that can be searched individually
    # Supports 1 - 6, default: 2
    heading_level: 2
    # Maximum amount of previews per search result
    # Default: 3
    previews: 3
    # Maximum amount of words to display before a matched word in the preview
    # Default: 5
    preview_words_before: 5
    # Maximum amount of words to display after a matched word in the preview
    # Default: 10
    preview_words_after: 10
    # Set the search token separator
    # Default: /[\s\-/]+/
    # Example: enable support for hyphenated search words
    tokenizer_separator: /[\s/]+/
    # Display the relative url in search results
    # Supports true (default) or false
    rel_url: true
    # Enable or disable the search button that appears in the bottom right corner of every page
    # Supports true or false (default)
    button: false

# page configurations

color_scheme: dark

aux_links:
    "GitHub":
        - "https://github.com/RahulARanger/MAL-Remainder"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
heading_anchors: true

# footer things

footer_content: "<a href='https://saythanks.io/to/RahulARanger'><img src='https://img.shields.io/badge/Say%20Thanks-!-1EAEDB.svg' title='If you like this project then let me know 😄'></a><br><br>Copyright (c) 2021 RahulARanger, Distributed by <a href='https://github.com/RahulARanger/MAL-Remainder/blob/master/LICENSE.txt'>MIT LICENSE.</a>"
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p" # i like this default format


gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/RahulARanger/MAL-Remainder" # the github URL for your repo
gh_edit_branch: "master"
gh_edit_source: docs
gh_edit_view_mode: "blob" 



callouts:
    comfy:
        # title:
        color: pink
        opacity: 0.34
    attention:
        title: Attention
        color: purple
    caution:
        title: Caution
        color: yellow
    danger:
        title: Danger
        color: red
    error:
        title: Error
        color: red
    highlight:
        color: yellow
        opacity: 0.5
    hint:
        title: Hint
        color: grey-dk
    important:
        title: Important
        color: green
    note:
        title: Note
        color: blue
    tip:
        title: Tip
        color: grey-dk
    warning:
        title: Warning
        color: red
