source "https://rubygems.org"

#     bundle exec jekyll serve

gem "jekyll", "~> 4.2.2"

# below is for the Github Pages only for local, comment that line
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  # START FOR GITHUB PAGES
  gem "github-pages"
  # END FOR GITHUB-PAGES
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

gem "webrick", "~> 1.7"

gem "jekyll-remote-theme"
gem "just-the-docs", github: "pdmosses/just-the-docs", branch: "callouts"

